# Generated by Django 3.2.10 on 2021-12-31 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfounder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ideas',
            new_name='Idea',
        ),
    ]
